export const SPACE_TYPES = [
  { id: "trade-show", label: "Trade Show", shortLabel: "Booth" },
  { id: "office", label: "Office", shortLabel: "Office" },
  { id: "bedroom", label: "Bedroom", shortLabel: "Bedroom" },
  { id: "bathroom", label: "Bathroom", shortLabel: "Bathroom" },
  { id: "living", label: "Living Room", shortLabel: "Living" },
  { id: "kitchen", label: "Kitchen", shortLabel: "Kitchen" },
  { id: "dining", label: "Dining Room", shortLabel: "Dining" },
  { id: "home", label: "Whole Home", shortLabel: "Home" },
];

export const SPACE_TYPE_IDS = new Set(SPACE_TYPES.map((spaceType) => spaceType.id));

export const DEFAULT_SPACE = {
  name: "TechWave Global Summit 2026",
  width: 20,
  depth: 30,
  spaceType: "trade-show",
  note: "Client-ready island booth plan with an LED feature wall, reception, demo zones, and AR handoff.",
};

export const SPACE_TEMPLATES = [
  {
    id: "pod-10x10",
    spaceType: "trade-show",
    name: "10 x 10 Demo Pod",
    width: 10,
    depth: 10,
    note: "Tight footprint for lead capture and quick demos.",
    items: [
      { type: "Banner", x: 0, y: 1, rotation: 0, label: "Aisle Banner" },
      { type: "Screen", x: 0, y: 1, rotation: 0, label: "Hero Wall" },
      { type: "Table", x: 2, y: 5, rotation: 0, label: "Demo Table" },
      { type: "Chair", x: 1, y: 7, rotation: 0, label: "Seat A" },
      { type: "Chair", x: 5, y: 7, rotation: 0, label: "Seat B" },
    ],
  },
  {
    id: "techwave-20x30",
    spaceType: "trade-show",
    name: "TechWave Global Summit 2026",
    width: 20,
    depth: 30,
    note: "Client plan with an LED wall, reception, demos, lounge seating, kiosks, banners, and greenery.",
    items: [
      { type: "Screen", x: 5, y: 2, rotation: 0, label: "TECHWAVE LED Wall" },
      { type: "Banner", x: 15, y: 4, rotation: 90, label: "Brand Banner" },
      { type: "Counter", x: 7, y: 19, rotation: 0, label: "Reception Counter" },
      { type: "Table", x: 12, y: 14, rotation: 0, label: "Demo Table" },
      { type: "Kiosk", x: 17, y: 10, rotation: 0, label: "Kiosk Podium" },
      { type: "RoundTable", x: 3, y: 15, rotation: 0, label: "Round Table" },
      { type: "Chair", x: 2, y: 14, rotation: 45, label: "Lounge Chair" },
      { type: "Chair", x: 5, y: 14, rotation: 315, label: "Lounge Chair" },
      { type: "Chair", x: 3, y: 18, rotation: 135, label: "Lounge Chair" },
      { type: "Chair", x: 14, y: 7, rotation: 0, label: "Lounge Chair" },
      { type: "Stool", x: 12, y: 16, rotation: 0, label: "Bar Stool" },
      { type: "Stool", x: 15, y: 16, rotation: 0, label: "Bar Stool" },
      { type: "Chair", x: 15, y: 22, rotation: 45, label: "Lounge Chair" },
      { type: "Chair", x: 17, y: 22, rotation: 315, label: "Lounge Chair" },
      { type: "RoundTable", x: 16, y: 23, rotation: 0, label: "Side Table" },
      { type: "Plant", x: 3, y: 5, rotation: 0, label: "Planter" },
      { type: "Plant", x: 14, y: 5, rotation: 0, label: "Planter" },
      { type: "Plant", x: 5, y: 25, rotation: 0, label: "Planter" },
    ],
  },
  {
    id: "theater-30x20",
    spaceType: "trade-show",
    name: "30 x 20 Theater Layout",
    width: 30,
    depth: 20,
    note: "Presentation-forward footprint built for larger crowds.",
    items: [
      { type: "Screen", x: 11, y: 1, rotation: 0, label: "Stage Screen" },
      { type: "Banner", x: 3, y: 1, rotation: 0, label: "Entrance Banner" },
      { type: "Banner", x: 24, y: 12, rotation: 0, label: "CTA Banner" },
      { type: "Counter", x: 1, y: 2, rotation: 90, label: "Reception" },
      { type: "Counter", x: 25, y: 2, rotation: 90, label: "Storage" },
      { type: "Table", x: 9, y: 10, rotation: 0, label: "Presentation Table" },
      { type: "Chair", x: 7, y: 14, rotation: 0, label: "Front Row A" },
      { type: "Chair", x: 10, y: 14, rotation: 0, label: "Front Row B" },
      { type: "Chair", x: 13, y: 14, rotation: 0, label: "Front Row C" },
      { type: "Chair", x: 16, y: 14, rotation: 0, label: "Front Row D" },
      { type: "Chair", x: 19, y: 14, rotation: 0, label: "Front Row E" },
    ],
  },
  {
    id: "executive-office-20x24",
    spaceType: "office",
    name: "Executive Office Suite",
    width: 20,
    depth: 24,
    note: "A client-facing office with a focused work zone, meeting area, storage, and presentation wall.",
    items: [
      { type: "Desk", x: 6, y: 4, rotation: 0, label: "Executive Desk" },
      { type: "OfficeChair", x: 8, y: 8, rotation: 180, label: "Task Chair" },
      { type: "OfficeChair", x: 6, y: 1, rotation: 0, label: "Guest Chair" },
      { type: "OfficeChair", x: 10, y: 1, rotation: 0, label: "Guest Chair" },
      { type: "Bookcase", x: 1, y: 3, rotation: 90, label: "Library Wall" },
      { type: "Screen", x: 5, y: 21, rotation: 180, label: "Presentation Display" },
      { type: "Sofa", x: 6, y: 14, rotation: 0, label: "Client Sofa" },
      { type: "CoffeeTable", x: 7, y: 18, rotation: 0, label: "Coffee Table" },
      { type: "Plant", x: 17, y: 20, rotation: 0, label: "Floor Plant" },
    ],
  },
  {
    id: "team-office-32x28",
    spaceType: "office",
    name: "Collaborative Team Office",
    width: 32,
    depth: 28,
    note: "A scalable open office with desks, collaboration seating, storage, and a shared display.",
    items: [
      { type: "Desk", x: 4, y: 4, rotation: 0, label: "Workstation 1" },
      { type: "Desk", x: 13, y: 4, rotation: 0, label: "Workstation 2" },
      { type: "Desk", x: 22, y: 4, rotation: 0, label: "Workstation 3" },
      { type: "OfficeChair", x: 6, y: 8, rotation: 180, label: "Task Chair 1" },
      { type: "OfficeChair", x: 15, y: 8, rotation: 180, label: "Task Chair 2" },
      { type: "OfficeChair", x: 24, y: 8, rotation: 180, label: "Task Chair 3" },
      { type: "DiningTable", x: 11, y: 15, rotation: 0, label: "Collaboration Table" },
      { type: "OfficeChair", x: 10, y: 19, rotation: 180, label: "Collaboration Chair" },
      { type: "OfficeChair", x: 19, y: 19, rotation: 180, label: "Collaboration Chair" },
      { type: "Bookcase", x: 1, y: 20, rotation: 90, label: "Shared Storage" },
      { type: "Screen", x: 11, y: 25, rotation: 180, label: "Team Display" },
    ],
  },
  {
    id: "primary-bedroom-14x18",
    spaceType: "bedroom",
    name: "Primary Bedroom",
    width: 14,
    depth: 18,
    note: "A balanced sleeping space with storage, bedside surfaces, and clear circulation.",
    items: [
      { type: "Bed", x: 4, y: 2, rotation: 0, label: "Queen Bed" },
      { type: "Nightstand", x: 1, y: 3, rotation: 0, label: "Left Nightstand" },
      { type: "Nightstand", x: 11, y: 3, rotation: 0, label: "Right Nightstand" },
      { type: "Rug", x: 3, y: 6, rotation: 0, label: "Area Rug" },
      { type: "Dresser", x: 4, y: 15, rotation: 180, label: "Low Dresser" },
      { type: "Wardrobe", x: 11, y: 11, rotation: 90, label: "Wardrobe" },
      { type: "Chair", x: 1, y: 13, rotation: 45, label: "Reading Chair" },
    ],
  },
  {
    id: "spa-bathroom-12x14",
    spaceType: "bathroom",
    name: "Spa Bathroom",
    width: 12,
    depth: 14,
    note: "A full bathroom layout with clear fixture footprints and a calm spa-style material palette.",
    items: [
      { type: "Vanity", x: 1, y: 1, rotation: 0, label: "Double Vanity" },
      { type: "Toilet", x: 8, y: 1, rotation: 0, label: "Toilet" },
      { type: "Bathtub", x: 1, y: 10, rotation: 180, label: "Soaking Tub" },
      { type: "Shower", x: 8, y: 9, rotation: 180, label: "Glass Shower" },
      { type: "Cabinet", x: 9, y: 5, rotation: 90, label: "Linen Cabinet" },
    ],
  },
  {
    id: "living-room-18x22",
    spaceType: "living",
    name: "Modern Living Room",
    width: 18,
    depth: 22,
    note: "Conversation-first living room with media, soft seating, storage, and a full-size rug footprint.",
    items: [
      { type: "Sofa", x: 5, y: 3, rotation: 0, label: "Three Seat Sofa" },
      { type: "Chair", x: 1, y: 9, rotation: 90, label: "Lounge Chair" },
      { type: "Chair", x: 14, y: 9, rotation: 270, label: "Lounge Chair" },
      { type: "CoffeeTable", x: 7, y: 9, rotation: 0, label: "Coffee Table" },
      { type: "Rug", x: 4, y: 7, rotation: 0, label: "Area Rug" },
      { type: "Sideboard", x: 5, y: 19, rotation: 180, label: "Media Console" },
      { type: "Screen", x: 4, y: 20, rotation: 180, label: "Media Display" },
      { type: "Plant", x: 15, y: 18, rotation: 0, label: "Floor Plant" },
    ],
  },
  {
    id: "kitchen-16x20",
    spaceType: "kitchen",
    name: "Island Kitchen",
    width: 16,
    depth: 20,
    note: "A practical kitchen work triangle with an island, appliance clearances, storage, and prep zones.",
    items: [
      { type: "KitchenIsland", x: 4, y: 8, rotation: 0, label: "Prep Island" },
      { type: "Stool", x: 5, y: 12, rotation: 180, label: "Island Stool 1" },
      { type: "Stool", x: 8, y: 12, rotation: 180, label: "Island Stool 2" },
      { type: "Refrigerator", x: 1, y: 1, rotation: 0, label: "Refrigerator" },
      { type: "Range", x: 6, y: 1, rotation: 0, label: "Range" },
      { type: "Sink", x: 10, y: 1, rotation: 0, label: "Sink Base" },
      { type: "Cabinet", x: 1, y: 16, rotation: 180, label: "Pantry Cabinet" },
      { type: "Cabinet", x: 5, y: 16, rotation: 180, label: "Storage Cabinet" },
    ],
  },
  {
    id: "dining-room-16x18",
    spaceType: "dining",
    name: "Dining Room",
    width: 16,
    depth: 18,
    note: "An eight-seat dining plan with serving storage and generous chair pullback room.",
    items: [
      { type: "DiningTable", x: 4, y: 6, rotation: 0, label: "Dining Table" },
      { type: "DiningChair", x: 4, y: 3, rotation: 0, label: "Dining Chair 1" },
      { type: "DiningChair", x: 7, y: 3, rotation: 0, label: "Dining Chair 2" },
      { type: "DiningChair", x: 10, y: 3, rotation: 0, label: "Dining Chair 3" },
      { type: "DiningChair", x: 4, y: 11, rotation: 180, label: "Dining Chair 4" },
      { type: "DiningChair", x: 7, y: 11, rotation: 180, label: "Dining Chair 5" },
      { type: "DiningChair", x: 10, y: 11, rotation: 180, label: "Dining Chair 6" },
      { type: "Sideboard", x: 4, y: 15, rotation: 180, label: "Serving Sideboard" },
      { type: "Plant", x: 13, y: 15, rotation: 0, label: "Floor Plant" },
    ],
  },
  {
    id: "whole-home-36x48",
    spaceType: "home",
    name: "Whole Home Concept",
    width: 36,
    depth: 48,
    note: "A scalable open-plan concept using partitions, doors, furniture, kitchen fixtures, and bedroom zones.",
    items: [
      { type: "Wall", x: 17, y: 0, rotation: 90, label: "Center Partition A" },
      { type: "Wall", x: 17, y: 8, rotation: 90, label: "Center Partition B" },
      { type: "Door", x: 17, y: 17, rotation: 90, label: "Hall Door" },
      { type: "Wall", x: 17, y: 21, rotation: 90, label: "Center Partition C" },
      { type: "Wall", x: 17, y: 29, rotation: 90, label: "Center Partition D" },
      { type: "Sofa", x: 4, y: 5, rotation: 0, label: "Living Sofa" },
      { type: "CoffeeTable", x: 6, y: 10, rotation: 0, label: "Living Coffee Table" },
      { type: "Rug", x: 3, y: 7, rotation: 0, label: "Living Rug" },
      { type: "KitchenIsland", x: 23, y: 8, rotation: 0, label: "Kitchen Island" },
      { type: "Refrigerator", x: 31, y: 2, rotation: 0, label: "Refrigerator" },
      { type: "Range", x: 25, y: 2, rotation: 0, label: "Range" },
      { type: "DiningTable", x: 23, y: 17, rotation: 0, label: "Dining Table" },
      { type: "Bed", x: 4, y: 31, rotation: 0, label: "Primary Bed" },
      { type: "Nightstand", x: 1, y: 33, rotation: 0, label: "Nightstand" },
      { type: "Dresser", x: 4, y: 43, rotation: 180, label: "Bedroom Dresser" },
      { type: "Vanity", x: 23, y: 33, rotation: 0, label: "Bathroom Vanity" },
      { type: "Toilet", x: 31, y: 33, rotation: 0, label: "Toilet" },
      { type: "Shower", x: 29, y: 41, rotation: 180, label: "Shower" },
    ],
  },
];

export function getTemplatesForSpaceType(spaceType) {
  return SPACE_TEMPLATES.filter((template) => template.spaceType === spaceType);
}

export function getSpaceTypeLabel(spaceType) {
  return SPACE_TYPES.find((entry) => entry.id === spaceType)?.label ?? "Space";
}
